@startuml
hide footbox
database "Zookeeper" as zk
database "Shared File\nSystem" as nfs
control "Overseer" as os
participant "Replica 1\n at node 1" as n1

n1->nfs: use dir core1
n1->zk:register
activate zk
n1->n1: goes down
zk->zk: conn timeout
deactivate zk
zk-->os: core1 down
os->os: wait some...
create participant "Replica 1\n at node 2" as n2
os->n2: create \nusing dir core1
n2->nfs:use dir core1
note left: Then recovery\n if more reps.



@enduml